version: '3'
services:
  nextjs:
    build: .
    tty: true
    restart: always
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      #コンテナ→ホストへの反映を早くするために:cached
      - .:/workspace:cached
      - nextjs-node-modules:/workspace/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
#node-modulesがバインドマウントされるのを回避
volumes:
  nextjs-node-modules:
